Repository rsksmart/rif-marketplace-cache, pull requests merged in 2020-11, with the labels that each got.

#384 fix(storage): makes periodsSinceLastPayout 0 if not positive
  src/services/storage/models/agreement.model.ts
Labels: bug, service: Storage

#395 feat: add general error message handler for comms
  src/communication/handlers.ts
Labels: blocked

#378 feat: adjust room topic computation
  config/test.json5
  src/communication/index.ts
  src/services/storage/index.ts
Labels: blocked

#408 fix: make contract address lower case in room topic
  src/communication/index.ts
Labels: bug

#419 docs: fixes endpoints descriptions
  README.md
Labels: documentation

#421 fix(storage): groups by provider to get min max available capacity
  src/services/storage/utils.ts
  test/unit/services/storage/services.spec.ts
Labels: bug
